import React,{useState}from"react";
const A=(v:any)=>Array.isArray(v)?v:[];
const S=(v:any)=>String(v??"");
const rows=(boards:any)=>{const r:any[]=[];A(boards).forEach((b:any)=>A(b.groups).forEach((g:any)=>A(g.items).forEach((i:any)=>r.push({b,g,i}))));return r};
const col=(s:any)=>{s=S(s).toLowerCase();return s.includes("done")?"#00c875":s.includes("review")?"#579bfc":s.includes("need")||s.includes("stuck")?"#e2445c":"#fdab3d"};
const key=(r:any)=>`${r.b.id}:${r.g.id}:${r.i.id}`;
function upd(p:any,r:any,f:any){p(r.b.id,(cur:any)=>({...cur,groups:A(cur.groups).map((g:any)=>g.id===r.g.id?{...g,items:A(g.items).map((it:any)=>it.id===r.i.id?f(it):it)}:g)}))}
function Head({t,s,a}:any){return <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div><h1 style={{margin:0}}>{t}</h1><small>{s}</small></div>{a}</div>}
export function MondayMini({mode,boards,onPatchBoard,onOpenBoard,user}:any){const rs=rows(boards);const[sel,setSel]=useState(rs[0]?key(rs[0]):"");const row=rs.find((x:any)=>key(x)===sel)||rs[0];const page={padding:24,background:"#f7f8fc",minHeight:"100%"};const card={background:"#fff",border:"1px solid #eceef5",borderRadius:16,padding:14};
function comment(){if(!row)return;const v=prompt("Comment / update","");if(v)upd(onPatchBoard,row,(it:any)=>({...it,comments:[...A(it.comments),`${new Date().toLocaleString()} - ${user}: ${v}`],updatedAt:new Date().toISOString()}))}
function attach(){if(!row)return;const v=prompt("Attachment name or link","");if(v)upd(onPatchBoard,row,(it:any)=>({...it,attachments:[...A(it.attachments),{id:Date.now(),name:v,by:user,at:new Date().toISOString()}],comments:[...A(it.comments),`Attached: ${v}`],updatedAt:new Date().toISOString()}))}
function auto(){let n=0;rs.forEach((r:any)=>upd(onPatchBoard,r,(it:any)=>{let x={...it,tags:A(it.tags),comments:A(it.comments)};if(/review/i.test(S(it.status))&&!x.tags.includes("Review")){x.tags=[...x.tags,"Review"];n++}if(/need|stuck|revision/i.test(S(it.status))&&!x.tags.includes("Blocker")){x.tags=[...x.tags,"Blocker"];n++}if(S(it.due)&&!x.tags.includes("Due Soon")){const d=new Date(it.due);const days=Math.round((d.getTime()-new Date().setHours(0,0,0,0))/86400000);if(days>=0&&days<=1){x.tags=[...x.tags,"Due Soon"];n++}}return{...x,updatedAt:new Date().toISOString()}}));alert(`Automation completed: ${n}`)}
if(mode==="calendar"){const g:any={};rs.filter((r:any)=>S(r.i.due)).forEach((r:any)=>{g[r.i.due]=[...(g[r.i.due]||[]),r]});return <div style={page}><Head t="Calendar View" s="Tasks grouped by due date."/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>{Object.keys(g).sort().map(d=><div key={d} style={card}><b>{d}</b>{g[d].map((r:any)=><button key={key(r)} onClick={()=>onOpenBoard(r.b.id,r.i.id)} style={{display:"block",width:"100%",marginTop:8,border:`1px solid #eee`,borderLeft:`5px solid ${col(r.i.status)}`,borderRadius:10,padding:10,background:"#fff",textAlign:"left"}}>{r.i.name}<br/><small>{r.b.name} - {r.i.owner||"No owner"}</small></button>)}</div>)}</div></div>}
if(mode==="timeline")return <div style={page}><Head t="Timeline / Gantt View" s="Simple timeline from start to due date."/><div style={card}>{rs.map((r:any)=><button key={key(r)} onClick={()=>onOpenBoard(r.b.id,r.i.id)} style={{display:"grid",gridTemplateColumns:"260px 1fr",gap:12,width:"100%",marginBottom:8,border:"1px solid #eee",borderRadius:10,padding:10,background:"#fff",textAlign:"left"}}><span><b>{r.i.name}</b><br/><small>{r.i.start||"no start"} to {r.i.due||"no due"}</small></span><span style={{height:18,background:"#f1f3f8",borderRadius:999}}><span style={{display:"block",height:"100%",width:"55%",background:col(r.i.status),borderRadius:999}}/></span></button>)}</div></div>;
if(mode==="files")return <div style={page}><Head t="Files & Activity" s="Attachments and task activity timeline."/><div style={{display:"grid",gridTemplateColumns:"300px 1fr",gap:16}}><div style={card}>{rs.map((r:any)=><button key={key(r)} onClick={()=>setSel(key(r))} style={{display:"block",width:"100%",marginBottom:8,padding:10,border:"1px solid #eee",borderRadius:10,background:key(r)===sel?"#eef4ff":"#fff",textAlign:"left"}}>{r.i.name}<br/><small>{A(r.i.attachments).length} files, {A(r.i.comments).length} updates</small></button>)}</div><div style={card}>{row&&<><h2>{row.i.name}</h2><button onClick={comment}>Add comment</button> <button onClick={attach}>Add attachment</button><h3>Attachments</h3>{A(row.i.attachments).map((x:any)=><div key={x.id||x.name}>file: {x.name}</div>)}<h3>Activity</h3>{A(row.i.comments).slice().reverse().map((c:any,i:number)=><div key={i} style={{borderLeft:"4px solid #0073ea",padding:8,marginTop:8,background:"#fafbff"}}>{typeof c==="string"?c:JSON.stringify(c)}</div>)}</>}</div></div></div>;
return <div style={page}><Head t="Automation Rules" s="Simple no-code rules." a={<button onClick={auto}>Run automation now</button>}/><div style={card}>Rules: Review tag, Blocker tag, Due Soon tag.</div></div>}
