import React,{useState}from"react";
const A=(v:any):any[]=>Array.isArray(v)?v:[];
const S=(v:any)=>String(v??"");
const R=(boards:any)=>{const out:any[]=[];A(boards).filter((b:any)=>!b?.archivedAt).forEach((b:any)=>A(b.groups).forEach((g:any)=>A(g.items).forEach((i:any)=>out.push({b,g,i}))));return out};
const K=(r:any)=>`${r.b.id}:${r.g.id}:${r.i.id}`;
const C=(v:any)=>{v=S(v).toLowerCase();return v.includes("done")||v.includes("approved")?"#00c875":v.includes("review")?"#579bfc":v.includes("need")||v.includes("stuck")||v.includes("revision")?"#e2445c":"#fdab3d"};
const D=(v:any)=>{const d=new Date(S(v));return Number.isNaN(d.getTime())?null:d};
function P({t,s,a}:any){return <div style={{display:"flex",justifyContent:"space-between",gap:12,marginBottom:16}}><div><div style={{fontSize:30,fontWeight:950}}>{t}</div><div style={{fontSize:13,color:"#676879"}}>{s}</div></div>{a}</div>}
function patch(p:any,r:any,f:any){p(r.b.id,(cur:any)=>({...cur,groups:A(cur.groups).map((g:any)=>g.id===r.g.id?{...g,items:A(g.items).map((it:any)=>it.id===r.i.id?f(it):it)}:g)}))}
export function MondayMini({mode,boards,onPatchBoard,onOpenBoard,user}:any){const rows=R(boards);const[sel,setSel]=useState(rows[0]?K(rows[0]):"");const row=rows.find((x:any)=>K(x)===sel)||rows[0];const card={background:"#fff",border:"1px solid #eceef5",borderRadius:16,padding:16};
function addComment(){if(!row)return;const v=prompt("Comment / update","");if(!v?.trim())return;patch(onPatchBoard,row,(it:any)=>({...it,comments:[...A(it.comments),`${new Date().toLocaleString()} • ${user}: ${v.trim()}`],updatedAt:new Date().toISOString()}))}
function addFile(){if(!row)return;const v=prompt("Attachment name or link","");if(!v?.trim())return;patch(onPatchBoard,row,(it:any)=>({...it,attachments:[...A(it.attachments),{id:Date.now(),name:v.trim(),createdBy:user,createdAt:new Date().toISOString()}],comments:[...A(it.comments),`Attached: ${v.trim()}`],updatedAt:new Date().toISOString()}))}
function runAuto(){let n=0;A(boards).forEach((b:any)=>onPatchBoard(b.id,(cur:any)=>({...cur,groups:A(cur.groups).map((g:any)=>({...g,items:A(g.items).map((it:any)=>{let x={...it,tags:A(it.tags),comments:A(it.comments)};const due=D(it.due);const days=due?Math.round((due.getTime()-new Date().setHours(0,0,0,0))/86400000):999;if(days>=0&&days<=1&&!x.tags.includes("Due Soon")){x.tags=[...x.tags,"Due Soon"];x.comments=[...x.comments,"Automation: Due Soon"];n++}if(/review/i.test(S(it.status))&&!x.tags.includes("Review")){x.tags=[...x.tags,"Review"];x.comments=[...x.comments,"Automation: Review"];n++}if(/need|stuck|revision/i.test(S(it.status))&&!x.tags.includes("Blocker")){x.tags=[...x.tags,"Blocker"];x.comments=[...x.comments,"Automation: Blocker"];n++}return{...x,updatedAt:new Date().toISOString()}})}))}))));alert(`Automation completed: ${n} update(s).`)}
if(mode==="calendar"){const g:any={};rows.filter((r:any)=>S(r.i.due)).forEach((r:any)=>{const d=D(r.i.due);const k=d?d.toISOString().slice(0,10):"No date";g[k]=[...(g[k]||[]),r]});return <div style={{padding:24,background:"#f7f8fc",minHeight:"100%"}}><P t="Calendar View" s="Tasks grouped by due date."/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14}}>{Object.keys(g).sort().map(k=><div key={k} style={card}><b>{k}</b>{g[k].map((r:any)=><button key={K(r)} onClick={()=>onOpenBoard(r.b.id,r.i.id)} style={{display:"block",width:"100%",marginTop:8,textAlign:"left",background:"#fff",border:"1px solid #eee",borderLeft:`5px solid ${C(r.i.status)}`,borderRadius:10,padding:10}}>{r.i.name}<div style={{fontSize:11,color:"#676879"}}>{r.b.name} • {r.i.owner||"No owner"}</div></button>)}</div>)}</div></div>}
if(mode==="timeline")return <div style={{padding:24,background:"#f7f8fc",minHeight:"100%"}}><P t="Timeline / Gantt View" s="Simple timeline from start to due date."/><div style={card}>{rows.map((r:any)=><button key={K(r)} onClick={()=>onOpenBoard(r.b.id,r.i.id)} style={{display:"grid",gridTemplateColumns:"260px 1fr",gap:12,width:"100%",marginBottom:8,textAlign:"left",background:"#fff",border:"1px solid #eee",borderRadius:10,padding:10}}><span><b>{r.i.name}</b><br/><small>{r.i.start||"no start"} → {r.i.due||"no due"}</small></span><span style={{height:18,background:"#f1f3f8",borderRadius:999}}><span style={{display:"block",height:"100%",width:"55%",background:C(r.i.status),borderRadius:999}}/></span></button>)}</div></div>;
if(mode==="files")return <div style={{padding:24,background:"#f7f8fc",minHeight:"100%"}}><P t="Files & Activity" s="Attachments and task activity timeline."/><div style={{display:"grid",gridTemplateColumns:"320px 1fr",gap:18}}><div style={card}>{rows.map((r:any)=><button key={K(r)} onClick={()=>setSel(K(r))} style={{width:"100%",textAlign:"left",marginBottom:8,background:K(r)===sel?"#eef4ff":"#fff",border:"1px solid #eee",borderRadius:10,padding:10}}>{r.i.name}<br/><small>{A(r.i.attachments).length} file(s) • {A(r.i.comments).length} update(s)</small></button>)}</div><div style={card}>{row&&<><h2>{row.i.name}</h2><button onClick={addComment}>Add comment</button> <button onClick={addFile}>Add attachment</button><h3>Attachments</h3>{A(row.i.attachments).map((x:any)=><div key={x.id||x.name} style={{border:"1px solid #eee",borderRadius:10,padding:10,marginTop:8}}>📎 {x.name}</div>)}<h3>Activity timeline</h3>{A(row.i.comments).slice().reverse().map((c:any,i:number)=><div key={i} style={{borderLeft:"4px solid #0073ea",background:"#fafbff",borderRadius:8,padding:10,marginTop:8}}>{typeof c==="string"?c:c?.text||JSON.stringify(c)}</div>)}</>}</div></div></div>;
return <div style={{padding:24,background:"#f7f8fc",minHeight:"100%"}}><P t="Automation Rules" s="Simple no-code rules." a={<button onClick={runAuto} style={{background:"#0073ea",color:"#fff",border:0,borderRadius:8,padding:"9px 12px",fontWeight:900}}>Run automation now</button>}/><div style={card}>Rules: due soon tag, review tag, blocker tag.</div></div>}
